name: Backend - Build & Test

run-name: "Backend - Build & Test for PR #${{ github.event.pull_request.number }}"

on:
  workflow_call:
  pull_request:

env:
  DOCKER_VENV: ".venv@docker"

jobs:
  build-backend:
    name: Build Backend Service
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: cd backend && docker build . -t http-backend

      - name: Set up Virtual Environment
        run: cd backend && docker run --rm --volume .:/app http-backend ./scripts/sync.sh

      - name: Linting
        run: cd backend && docker run --rm --volume .:/app http-backend ./scripts/lint.sh

      - name: Run Unit Tests
        run: cd backend && docker run --rm --volume .:/app http-backend /app/${{ env.DOCKER_VENV }}/bin/pytest tests/unit
