name: Backend - Build & Test

run-name: "Backend - Build & Test for PR #${{ github.event.pull_request.number }}"

on:
  workflow_call:
  pull_request:

jobs:
  build-backend:
    name: Build Backend Service
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: cd backend && docker build . -t http-backend

      - name: Linting
        run: cd backend && docker run --rm http-backend ./scripts/lint.sh

