name: Pull Request Labeler

run-name: Labelling PR \#${{ github.event.pull_request.number }}

on: [pull_request]

jobs:
  pr-size-labeler:
    name: Label PR Size
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write  # if it needs to create new labels that do not exist

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

